apiVersion: v1
kind: Service
metadata:
  name: ftpserver
  labels:
    name: ftpserver
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ftpserver
  ports:
  - name: ftpserver-21
    port: 21
    targetPort: ftpserver-21
    protocol: TCP
  - name: ftpserver-20
    port: 20
    targetPort: ftpserver-20
    protocol: TCP
  - name: ftpserver-sftp
    port: 22
    targetPort: ftpserver-sftp
    protocol: TCP
  - name: ftpserver-pas00
    port: 20000
    targetPort: ftpserver-pas00
    protocol: TCP
  - name: ftpserver-pas01
    port: 20001
    targetPort: ftpserver-pas01
    protocol: TCP
  - name: ftpserver-pas02
    port: 20002
    targetPort: ftpserver-pas02
    protocol: TCP
  - name: ftpserver-pas03
    port: 20003
    targetPort: ftpserver-pas03
    protocol: TCP
  - name: ftpserver-pas04
    port: 20004
    targetPort: ftpserver-pas04
    protocol: TCP
  - name: ftpserver-pas05
    port: 20005
    targetPort: ftpserver-pas05
    protocol: TCP
  - name: ftpserver-pas06
    port: 20006
    targetPort: ftpserver-pas06
    protocol: TCP
  - name: ftpserver-pas07
    port: 20007
    targetPort: ftpserver-pas07
    protocol: TCP
  - name: ftpserver-pas08
    port: 20008
    targetPort: ftpserver-pas08
    protocol: TCP
  - name: ftpserver-pas09
    port: 20009
    targetPort: ftpserver-pas09
    protocol: TCP
  - name: ftpserver-pas10
    port: 20010
    targetPort: ftpserver-pas10
    protocol: TCP
  - name: ftpserver-pas11
    port: 20011
    targetPort: ftpserver-pas11
    protocol: TCP
  - name: ftpserver-pas12
    port: 20012
    targetPort: ftpserver-pas12
    protocol: TCP
  - name: ftpserver-pas13
    port: 20013
    targetPort: ftpserver-pas13
    protocol: TCP
  - name: ftpserver-pas14
    port: 20014
    targetPort: ftpserver-pas14
    protocol: TCP
  - name: ftpserver-pas15
    port: 20015
    targetPort: ftpserver-pas15
    protocol: TCP
  - name: ftpserver-pas16
    port: 20016
    targetPort: ftpserver-pas16
    protocol: TCP
  - name: ftpserver-pas17
    port: 20017
    targetPort: ftpserver-pas17
    protocol: TCP
  - name: ftpserver-pas18
    port: 20018
    targetPort: ftpserver-pas18
    protocol: TCP
  - name: ftpserver-pas19
    port: 20019
    targetPort: ftpserver-pas19
    protocol: TCP
  - name: ftpserver-pas20
    port: 20020
    targetPort: ftpserver-pas20
    protocol: TCP
  - name: ftpserver-pas21
    port: 20021
    targetPort: ftpserver-pas21
    protocol: TCP
  - name: ftpserver-pas22
    port: 20022
    targetPort: ftpserver-pas22
    protocol: TCP
  - name: ftpserver-pas23
    port: 20023
    targetPort: ftpserver-pas23
    protocol: TCP
  - name: ftpserver-pas24
    port: 20024
    targetPort: ftpserver-pas24
    protocol: TCP
  - name: ftpserver-pas25
    port: 20025
    targetPort: ftpserver-pas25
    protocol: TCP
  - name: ftpserver-pas26
    port: 20026
    targetPort: ftpserver-pas26
    protocol: TCP
  - name: ftpserver-pas27
    port: 20027
    targetPort: ftpserver-pas27
    protocol: TCP
  - name: ftpserver-pas28
    port: 20028
    targetPort: ftpserver-pas28
    protocol: TCP
  - name: ftpserver-pas29
    port: 20029
    targetPort: ftpserver-pas29
    protocol: TCP
  - name: ftpserver-pas30
    port: 20030
    targetPort: ftpserver-pas30
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ftpserver-admin
  labels:
    name: ftpserver-admin
  namespace: default
spec:
  type: NodePort
  selector:
    app: ftpserver
  ports:
  - name: ftpserver-http
    port: 80
    targetPort: ftpserver-http
    protocol: TCP
